---
output:
  word_document: default
  html_document: default
---

```{r}
library(tidyverse)
Telecom <- read_csv("Telecom.csv")

```

```{r}
Telecom$MonthlyCharges
is.na(Telecom$MonthlyCharges)
summarize(Telecom, count = sum(is.na(MonthlyCharges)))
mutate(Telecom, MonthlyCharges = replace(MonthlyCharges, is.na(MonthlyCharges),
                   median(MonthlyCharges, na.rm = TRUE)))

Telecom
```



```{r}
Telecom <- mutate(Telecom, MonthlyCharges = replace(MonthlyCharges, is.na(MonthlyCharges),median(MonthlyCharges, na.rm = TRUE)))
Telecom

Telecom <- mutate(Telecom, TotalCharges = replace(TotalCharges, TotalCharges == "na", NA))
Telecom

Telecom <- mutate(Telecom, TotalCharges = replace(TotalCharges, TotalCharges == "N/A", NA))
Telecom

Telecom$TotalCharges <- as.numeric(Telecom$TotalCharges)

Telecom <- mutate(Telecom, TotalCharges = replace(TotalCharges, is.na(TotalCharges),mean(TotalCharges, na.rm = TRUE)))
Telecom

Telecom <-  mutate(Telecom, PaymentMethod = replace(PaymentMethod, PaymentMethod ==  "--", NA))
Telecom

Telecom <- mutate(Telecom,PaymentMethod = replace(PaymentMethod, is.na(PaymentMethod), "unavailable"))
Telecom
```

```{r}
Telecom$TotalCharges <- as.numeric(Telecom$TotalCharges)

Telecom <- Telecom %>%
  mutate(MonthlyCharges = replace(MonthlyCharges, is.na(MonthlyCharges),median(MonthlyCharges, na.rm = TRUE))) %>%
  mutate(TotalCharges = replace(TotalCharges, TotalCharges == "na", NA)) %>%
  mutate(TotalCharges = replace(TotalCharges, TotalCharges == "N/A", NA)) %>%
  mutate(TotalCharges = replace(TotalCharges, is.na(TotalCharges),mean(TotalCharges, na.rm = TRUE))) %>%
  mutate(PaymentMethod = replace(PaymentMethod, PaymentMethod ==  "--", NA)) %>%
  mutate(PaymentMethod = replace(PaymentMethod, is.na(PaymentMethod), "unavailable"))

```
